### ISSUE TITLE
Jetbrains Cyan Light

### ISSUE THREAD

**Issue by atahrijouti** [zed-industries/extensions#1127]
### Check for existing issues

- [X] Completed

## Preview
![image](https://github.com/user-attachments/assets/c2c4d5b5-f7df-45f2-9a6d-d4b0af778454)

![image](https://github.com/user-attachments/assets/272dafa3-31cd-4627-8bba-2d12b3726d40)

![image](https://github.com/user-attachments/assets/1e4e1216-70b8-4d45-b690-b06c128dc57d)

### Plugin page
https://plugins.jetbrains.com/plugin/12102-cyan-light-theme

### Theme repo
https://github.com/OlyaB/CyanTheme

### Note
Upon looking at the code of the theme, I saw that the editor settings inherit options from a built-in theme within Jetbrains IDEs. So I wrote a script that consolidated the two themes into one overriding the parent theme values with the child values. [consolidated.json](https://github.com/user-attachments/files/16365683/consolidated.json)

**Original code**
- Editor Color Scheme
  - [Cyan Light](https://github.com/OlyaB/CyanTheme/blob/master/resources/themes/cyanScheme.xml)
  - [Parent Theme (Line 2 to Line 1491)](https://github.com/JetBrains/intellij-community/blob/master/platform/platform-resources/src/DefaultColorSchemesManager.xml#L2:L1491)

- UI Color Scheme https://github.com/OlyaB/CyanTheme/blob/master/src/Cyan.theme.json

**Comment by blaqat** [comment]
#### Working on this! ([Repo](https://github.com/biaqat/cyan-light-theme-zed/tree/284df363604a2a2bb2bb4ab75691fa836a364a58))
<img src="https://github.com/bIaqat/cyan-light-theme-zed/raw/main/assets/cyan-light.png" width="500">

**Comment by blaqat** [comment]
This theme extension has been merged, can be closed if everything looks alright!

**Comment by wooowchik** [comment]
![Screenshot from 2024-08-07 05-05-53](https://github.com/user-attachments/assets/1b7c1727-aab1-4f54-9d5a-14e4de63700f)
In my case pretty everything is off from the intended original theme

file explorer colors totally off;
terminal colors totally off;
the colors of the code inside the editor totally off.

I don't understand what causes this issue. 
![Screenshot from 2024-08-07 05-12-21](https://github.com/user-attachments/assets/cdc18077-55a9-427d-a9e0-f92ce19f3b91)

**Comment by blaqat** [comment]
Main issue is you are on an old version, but that's half my fault since the repo I linked in my first comment was one tied to the first commit for some reason.. [Updating](https://github.com/bIaqat/cyan-light-theme-zed) or using the one in the extensions and using the newest version there should fix ur editor highlights.

As for the terminal and file explorer, I don't plan on changing those highlights from what they are in the merged version unless there are contrast issues. Feel free to swap the blue and green to match what you like in your personal set up
<img src="https://github.com/user-attachments/assets/146879f8-842a-47bb-ba0d-379d11c513de" width="400">

**Comment by wooowchik** [comment]
> Main issue is you are on an old version, but that's half my fault since the repo I linked in my first comment was one tied to the first commit for some reason.. [Updating](https://github.com/bIaqat/cyan-light-theme-zed) or using the one in the extensions and using the newest version there should fix ur editor highlights.
> 
> As for the terminal and file explorer, I don't plan on changing those highlights from what they are in the merged version unless there are contrast issues. Feel free to swap the blue and green to match what you like in your personal set up <img alt="" width="400" src="https://private-user-images.githubusercontent.com/70248258/355667039-146879f8-842a-47bb-ba0d-379d11c513de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTE4NzksIm5iZiI6MTcyMzAxMTU3OSwicGF0aCI6Ii83MDI0ODI1OC8zNTU2NjcwMzktMTQ2ODc5ZjgtODQyYS00N2JiLWJhMGQtMzc5ZDExYzUxM2RlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA2MTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNTgyMTlmOGQzMDNjYjU5NDdhMjFkNGEzYmI0YzE5MjA1NTRkNzRjOTAyNDM5MGFiMjQ4MDczNjg1YzgwNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S6GTRLVDua9H9L9WxD03AmlBKqp6eqYG6zir62nJ_dE">

Your original theme is perfect, the issue on my editor is that it decides to switch my File explorer to faded green on white background and also other minor issues, which cannot be explained.
Basically it's like it don't obey the directive inside the theme itself, maybe because some cache issue or maybe because Wayland......

**Comment by atahrijouti** [comment]
@wooowchik Does it do it on all kinds of projects? the Green color font  in the file explorer is intended to mean : this a a new file added to git I think

**Comment by atahrijouti** [comment]
Here is an example

1. git init
2. touch haha.rs otherfile.rs "yet another file"
![image](https://github.com/user-attachments/assets/27f15087-3cd2-4aab-8999-2e2b49458703)

The above picture is an expected result

**Comment by wooowchik** [comment]
> @wooowchik Does it do it on all kinds of projects? the Green color font in the file explorer is intended to mean : this a a new file added to git I think

It's spontaneous, some times it does some time is not.

However, this is how its intended to look like:
![Screenshot from 2024-08-07 20-04-52](https://github.com/user-attachments/assets/f9e50441-eca1-4912-963c-d3d76e02a9bd)

**Comment by bIaqat** [comment]
That's the git file modified color
Green is created, Yellow is modified, the lighter grey is gitignored etc
What you had in the original screenshot was correctly green for created files

**Comment by wooowchik** [comment]
> in

Ok, thnks.

**Comment by wooowchik** [comment]
> the lighter grey is gitignored etc

In my case this lighter grey is looking very, very weak on the background of my File Explorer.
It looks such weak to me, that it's like faded away or something, hard to explain with word + my English is pretty weak too.

**Comment by wooowchik** [comment]
My last _post scriptum_.
I'm not a very big fan of dark themes, because they really tease my eyes, but I must to admit that **Material Dark** theme is actually the only one having all the colors perfectly matching the intonation of background/foreground etc.
In fact the color matching inside this theme is such nice that even if it's pretty dark theme I can still use it without suffering from eye fatigue.
![Screenshot from 2024-08-09 05-24-50](https://github.com/user-attachments/assets/23a31151-7d18-42bf-b023-9b75a57f9073)
