### ISSUE TITLE
SML

### ISSUE THREAD

**Issue by denx20** [zed-industries/extensions#133]
### Check for existing issues

- [x] Completed

### Language

SML (Standard ML)

### Tree Sitter parser link

- https://github.com/stonebuddha/tree-sitter-sml
- https://github.com/tautologico/tree-sitter-standardml
- https://github.com/MatthewFluet/tree-sitter-sml

### Language server link

https://github.com/azdavis/millet

**Comment by omarjatoi** [comment]
https://github.com/omarjatoi/zed-sml currently works for syntax highlighting and providing outlines (`CMD` + `o`), but the language server is currently not working. I believe the issue is that the release binary, when downloaded from GitHub, is unable to run due to a "macOS Cannot Verify That This App Is Free from Malware" error which does not bubble up to the user in any way.

I'm working on figuring out how to fix that, but in the meanwhile basic support is there.

I'll add it to https://github.com/zed-industries/extensions once I have the language server working.
