### ISSUE TITLE
Protobuf

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/extensions#146]
### Check for existing issues

- [X] Completed

### Language

Protobuf

### Tree Sitter parser link

https://github.com/mitchellh/tree-sitter-proto

### Language server link

https://github.com/bufbuild/buf-language-server

### Misc notes

A user requested that we support protobuf files.

It seems like no official grammars exists for Tree Sitter.  The one I linked seems like the only real choice.  We might need to write our own grammar.

The linked language server (suggested by the same user) is still being developed, but it seems like the [team](https://buf.build) building it is pretty professional, so I assume this will eventually be the standard.  The other language server offerings seem to be abandoned and not finished.

**Comment by scbizu** [comment]
Hi Team , I am trying to migrate my editor from VSCode , but without protobuf ls , I cannot navigate efficiently on the huge protobuf repo . 

And I find out that Zed provides the [Extension Trait](https://docs.rs/zed_extension_api/latest/zed_extension_api/trait.Extension.htm) , but without LSP `Definition` , I still cannot impl the extension by myself , any plans to add more LSP interface exported to Extensions ?

OFF TOPIC: I forked the buf's [vscode-buf](https://github.com/scbizu/vscode-buf) by myself , and adds the [bufls](https://github.com/scbizu/buf-language-server) integration , so I want to port it to Zed (because Zed's  SPEED  really shocked me 🚀 )

**Comment by notpeter** [comment]
There is an official Zed Extension for Protobuf.
<img width="602" alt="Screenshot 2024-12-10 at 18 43 33" src="https://github.com/user-attachments/assets/5d5d90d2-bb13-4c7e-96fe-f915469c068e">

The source is currently in-tree under: [extensions/proto](https://github.com/zed-industries/zed/tree/main/extensions/proto).

It needs [better docs](https://github.com/zed-industries/zed/blob/main/docs/src/languages/proto.md?plain=1), but with some configuration has been reported to work with either `buf` or `protobuf-language-server`.
