### ISSUE TITLE
Leaf, Swift, SwiftUI

### ISSUE THREAD

**Issue by Muning69** [zed-industries/extensions#200]
### Check for existing issues

- [X] Completed

### Language

Leaf、Swift、SwiftUI

**Comment by JosephTLyons** [comment]
I'm going to close this issue out because we have Swift. For the other remaining languages, feel free to open new issues, 1 per language, so we can track interest in them separately.

<img width="724" alt="SCR-20241110-bpkf" src="https://github.com/user-attachments/assets/b232c86d-1a9b-43a4-9035-7ce4a8cf4687">
