### ISSUE TITLE
Highlights for cobol programming language

### ISSUE THREAD

**Issue by Seidon1984** [zed-industries/extensions#585]
### Check for existing issues

- [X] Completed

### Language

Cobol

**Comment by JosephTLyons** [comment]
Hey @Seidon1984,

This issue appears to be a duplicate of:

- https://github.com/zed-industries/extensions/issues/132

Would you mind upvoting the linked issue with a thumbs up (👍) so that we can keep all the votes in one place? I'll close this one out as a duplicate. If this is a mistake, please reopen this issue with a comment explaining the difference.
